
services:
    # image place
    places:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: places
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - laravel

    # nginx
    nginx:
        image: nginx
        container_name: nginx
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - laravel

    # postgres
    postgres:
        image: postgres:16.1
        container_name: postgres
        restart: unless-stopped
        environment:
            POSTGRES_DB: ${DB_DATABASE:-places}
            POSTGRES_USER: ${DB_USERNAME:-places}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_SCHEMA: ${DB_SCHEMA:-places}
        ports:
            - "5432:5432"
        networks:
            - laravel

    #rede bridge
networks:
    laravel:
        driver: bridge